version: '3'
services:
  nestjs-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: npm run dev
    # Optionally, you can add a restart policy if you want it to auto-restart in case of failure.
    restart: unless-stopped
